# Taller Naive Bayes


In [ ]:
import pandas as pd

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
Solicitantes = pd.read_excel("/content/drive/MyDrive/EAFIT/0. SolicitantesCrédito.xlsx")
Solicitantes

Unnamed: 0  Edad    Sexo Estado civil  Hijos  Perscargo  Estrato  \
0              1    38      NR       Casado      1          0        3   
1              2    51      NR     Separado      6          1        4   
2              3    37   Mujer       Casado      2          0        3   
3              4    29      NR     Separado      1          0        2   
4              5    42   Mujer       Casado      3          4        2   
...          ...   ...     ...          ...    ...        ...      ...   
8373        8374    31  Hombre      Soltero      2          0        5   
8374        8375    38  Hombre     Separado      0          0        3   
8375        8376    43   Mujer       Casado      1          2        2   
8376        8377    37   Mujer       Casado      1          2        3   
8377        8378    24      NR      Soltero      0          0        2   

     Nivel de estudios  Tipo de contrato  Ingresos  ...  Plazo    Cuota (COP)  \
0            Bachiller           Ninguno   5424576  ...     48   82691.506204   
1              Técnico           Ninguno   1144064  ...     36   22781.212598   
2            Tecnólogo        Indefinido   2069853  ...     36   46294.596244   
3            Tecnólogo           Ninguno   1893080  ...     24   69564.950015   
4      Especializacion           Ninguno   3000367  ...     24  112478.307883   
...                ...               ...       ...  ...    ...            ...   
8373         Bachiller        Indefinido   5891088  ...     48  115108.056436   
8374         Bachiller  Labor Contratada   3092079  ...     36   96789.562091   
8375         Tecnólogo           Ninguno   2542007  ...     36   49713.608249   
8376         Tecnólogo        Indefinido   5677067  ...     36  163602.818587   
8377         Tecnólogo        Indefinido   1950392  ...     36   69024.928055   

                ConoCliente          Garantia            RespPat  \
0        Buenas Referencias      Sin Codeudor     Sin Patrimonio   
1        Buenas Referencias      Sin Codeudor  Prop.sin Hipoteca   
2        Buenas Referencias  Con Codeudor(es)     Sin Patrimonio   
3        Buenas Referencias  Con Codeudor(es)     Sin Patrimonio   
4        Buenas Referencias  Con Codeudor(es)     Sin Patrimonio   
...                     ...               ...                ...   
8373  Buena Experiencia CFB      Sin Codeudor     Sin Patrimonio   
8374     Buenas Referencias      Sin Codeudor  Prop.sin Hipoteca   
8375     Buenas Referencias      Sin Codeudor     Sin Patrimonio   
8376     Buenas Referencias  Con Codeudor(es)     Sin Patrimonio   
8377     Buenas Referencias      Sin Codeudor     Sin Patrimonio   

                      MoraCome  PreApr  Prob.Default (PD)       Score  \
0     Con Experiencia sin Mora     1.0           0.041659  582.478943   
1     Con Experiencia sin Mora     1.0           0.234951  479.839966   
2     Con Experiencia sin Mora     0.0           0.170330  417.653107   
3     Con Experiencia sin Mora     1.0           0.201659  316.791107   
4     Con Experiencia sin Mora     1.0           0.140929  441.809570   
...                        ...     ...                ...         ...   
8373  Con Experiencia sin Mora     1.0           0.035120  659.471375   
8374  Con Experiencia sin Mora     1.0           0.101976  465.011536   
8375  Con Experiencia sin Mora     1.0           0.156707  423.237305   
8376  Con Experiencia sin Mora     1.0           0.037719  592.670837   
8377  Con Experiencia sin Mora     NaN                NaN         NaN   

           LGD  
0     0.063702  
1     0.465636  
2     0.290071  
3     0.278389  
4     0.203359  
...        ...  
8373  0.066962  
8374  0.165936  
8375  0.247763  
8376  0.051356  
8377       NaN  

[8378 rows x 35 columns]

In [ ]:
Solicitantes.shape

(8378, 35)

In [ ]:
### 3. Eliminamos los registros donde PreAp esta vacio
XD = Solicitantes.dropna(subset=['PreApr'])

In [ ]:
Solicitantes.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8378 entries, 0 to 8377
Data columns (total 35 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   Unnamed: 0               8378 non-null   int64  
 1   Edad                     8378 non-null   int64  
 2   Sexo                     8378 non-null   object 
 3   Estado civil             8378 non-null   object 
 4   Hijos                    8378 non-null   int64  
 5   Perscargo                8378 non-null   int64  
 6   Estrato                  8378 non-null   int64  
 7   Nivel de estudios        8378 non-null   object 
 8   Tipo de contrato         8378 non-null   object 
 9   Ingresos                 8378 non-null   int64  
 10  Egresos                  8378 non-null   int64  
 11  Tipo de actividad        8378 non-null   object 
 12  Tipo de vivienda         8378 non-null   object 
 13  Total Activos            8378 non-null   float64
 14  Total pasivos           

In [ ]:
## Escojo solo las variables que voy a usar como independiente.
XD = XD[["Edad", "Hijos", "Perscargo", "Estrato", "Ingresos", "Egresos", "Monto (EAD)", "Plazo", "Cuota (COP)"]]

In [ ]:
## Escojemos las variables independientes
yd = Solicitantes["PreApr"].dropna()

In [ ]:
### Importamos las librerias que necesitamos
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.naive_bayes import GaussianNB

In [ ]:
### Convierto los dataset a array
XDArray = np.array(XD)
ydArray = np.array(yd)

In [ ]:
### ENTRENAMOS EL MODELO (FASE TRAIN)
modeloNB = GaussianNB()
modeloNB.fit(XDArray, ydArray)

GaussianNB()

In [ ]:
## Predecimos los yd (Etapa test)
ydPred = modeloNB.predict(XDArray)

In [ ]:
### Matriz de confusion
from sklearn.metrics import confusion_matrix

In [ ]:
cm = confusion_matrix(ydArray, ydPred)
cm

array([[2539,  420],
       [1041, 1842]])

In [ ]:
## Extraer los valores de la matriz de confusión
VN = cm[0,0]; FP = cm[0,1]; FN = cm[1,0]; VP = cm[1,1]

In [ ]:
## Exactitud
exactitud = (VP+VN)/ cm.sum()

## Error
error = (FP+FN)/ cm.sum()

## Precisión
precision = VP/(FP+VP)

## Sensibilidad
sensibilidad = VP/(VP+FN)

## Especificidad
especificidad = VN/(FP+VN)

In [ ]:
## Imprimo la Información
print(f'La Exactitud del modelo es:     {exactitud:.2%}')
print(f'El Error del modelo es:         {error:.2%}')
print(f'La Precisión del modelo es:     {precision:.2%}')
print(f'La sensibilidad del modelo es:  {sensibilidad:.2%}')
print(f'La Especificidad del modelo es: {especificidad:.2%}')

La Exactitud del modelo es:     74.99%
El Error del modelo es:         25.01%
La Precisión del modelo es:     81.43%
La sensibilidad del modelo es:  63.89%
La Especificidad del modelo es: 85.81%


In [ ]:
# Filtro los que no tienen clasificacion (No tienen valor en la columna PreApr)
XDGener = Solicitantes[Solicitantes["PreApr"].isna()]

In [ ]:
## Filtro las variables
XDGener = XDGener[["Edad", "Hijos", "Perscargo", "Estrato", "Ingresos", "Egresos", "Monto (EAD)", "Plazo", "Cuota (COP)"]]

In [ ]:
# Las convierto en Arreglos
XDGenerArray = np.array(XDGener)

array([[3.80000000e+01, 3.00000000e+00, 0.00000000e+00, ...,
        7.91312558e+05, 6.00000000e+01, 2.00941380e+04],
       [4.70000000e+01, 0.00000000e+00, 0.00000000e+00, ...,
        1.21301418e+05, 4.80000000e+01, 3.56322911e+03],
       [4.60000000e+01, 0.00000000e+00, 1.00000000e+00, ...,
        3.17445619e+06, 3.00000000e+00, 1.09005416e+06],
       ...,
       [3.20000000e+01, 0.00000000e+00, 1.00000000e+00, ...,
        1.01385156e+06, 3.60000000e+01, 3.66531625e+04],
       [3.50000000e+01, 2.00000000e+00, 1.00000000e+00, ...,
        2.15623904e+06, 1.80000000e+01, 1.37580518e+05],
       [2.40000000e+01, 0.00000000e+00, 0.00000000e+00, ...,
        1.90927674e+06, 3.60000000e+01, 6.90249281e+04]])

In [ ]:
# Generalizar (Las predicciones para los solicitantes faltantes)
ydGner = modeloNB.predict(XDGenerArray)

array([0., 0., 1., ..., 0., 0., 0.])

In [ ]:
ydGenerSerie = pd.Series(ydGner, index= Solicitantes[Solicitantes["PreApr"].isna()].index )
ydGenerSerie

6       0.0
7       0.0
11      1.0
13      0.0
16      0.0
       ... 
8357    0.0
8358    0.0
8367    0.0
8372    0.0
8377    0.0
Length: 2536, dtype: float64

In [ ]:
### Completamos la base de datos Principal
Solicitantes["PreApr"].fillna(ydGenerSerie, inplace=True)

/tmp/ipython-input-3857969632.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  Solicitantes["PreApr"].fillna(ydGenerSerie, inplace=True)


In [ ]:
Solicitantes.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8378 entries, 0 to 8377
Data columns (total 35 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   Unnamed: 0               8378 non-null   int64  
 1   Edad                     8378 non-null   int64  
 2   Sexo                     8378 non-null   object 
 3   Estado civil             8378 non-null   object 
 4   Hijos                    8378 non-null   int64  
 5   Perscargo                8378 non-null   int64  
 6   Estrato                  8378 non-null   int64  
 7   Nivel de estudios        8378 non-null   object 
 8   Tipo de contrato         8378 non-null   object 
 9   Ingresos                 8378 non-null   int64  
 10  Egresos                  8378 non-null   int64  
 11  Tipo de actividad        8378 non-null   object 
 12  Tipo de vivienda         8378 non-null   object 
 13  Total Activos            8378 non-null   float64
 14  Total pasivos           

#CONCLUSIONES
Con el nuevo escenario, al usar más variables, el modelo mejora en general su desempeño, ya que aumenta la exactitud y disminuye el error. Esto ocurre porque el modelo logra identificar mejor los casos positivos, reduciendo los falsos negativos y mejorando la sensibilidad. Es decir, se le escapan menos casos importantes que antes por tener mas informacion.

Sin embargo, esta mejora hace que el modelo también cometa un poco más de falsos positivos, por lo que la especificidad y la precisión bajan levemente. el modelo es mejor detectando positivos, pero a veces se equivoca marcando como positivo algo que no lo es.

En conclusión, agregar más variables ayuda a que el modelo entienda mejor los datos, pero también cambia el equilibrio entre aciertos y errores. Por eso, no siempre más variables significa un modelo perfecto, sino uno que debe evaluarse según el objetivo del análisis.